openapi: 3.0.0
info:
  title: Leaderboard API API
  version: 1.0.0
  contact:
    email: sam@pizette.org
servers:
  - url: http://localhost:3000/api/users
    description: Leaderboard API
tags:
  - name: users
    description: User operations
paths:
  /users:
    get:
      summary: get users
      tags:
        - users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#components/schemas/User'
                  pagination:
                    type: object
                    properties:
                      page:
                        type: integer
                      limit:
                        type: integer
                      length:
                        type: integer
        '404':
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /users/{id}:
    get:
      tags:
        - users
      summary: get user by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: the user ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
      example:
        _id: 9a96c347742440fe9fcdcff5b8f706e0